const int Pin_Relay_1   = 12;//relay 10A load max.
const int Pin_Relay_2   = 13;//relay 10A load max.
const int Pin_StatusLed = 16;
const int Pin_DHT       = 14;//pull-up 10K resistor	
const int Pin_Button_1  = 2;
const int Pin_Button_2  = 0;//pull-up 10K resistor	
const int Pin_IO_15  = 15;
const int Pin_IO_4  = 4;//DHT22//pull-up 4.7K resistor, can be disconnected	
const int Pin_IO_5  = 5;//DHT22//pull-up 4.7K resistor, can be disconnected	
