#include "Arduino.h"

const String header =  "HTTP/1.1 200 OK\r\nContent-Type: text/html\r\n";
const String response =
"<!DOCTYPE html><html><head><title>Kettle</title>"
"<script>"
    "function LoadSSE(){"
        "var source = new EventSource(\"/stats\");"
        "source.onmessage = function(event) {"
            "console.log(event);"
        "};"
        "source.addEventListener('message', function(e) {"
            "document.getElementById(\"result\").innerHTML += e.data + \"<br>\";"
            "document.getElementById(\"result\").scrollTop += 30;"
        "}, false);"
        "source.addEventListener('temperature', function(e) {"
            "document.getElementById('temperature').innerHTML = 'Kettle Temperature: ' + e.data + ' C' + \"<br>\";"
        "}, false);"
        "source.addEventListener('open', function(e) {"
            "document.getElementById(\"result\").innerHTML += 'OPENED' + e + \"<br>\";"
        "}, false);"
        "source.addEventListener('error', function(e) {"
          "if (e.readyState == EventSource.CLOSED) {"
          "document.getElementById(\"result\").innerHTML += 'Lost connection';"
          "}"
        "}, false);"
    "}"
    "function CallApi(endpoint) {"
    "var xhttp = new XMLHttpRequest();"
    "xhttp.onreadystatechange = function() {"
        "if (this.readyState == 4 && this.status == 200) {"
           //"alert('Doing ' + endpoint);"
        "}};"
    "xhttp.open('GET', endpoint, true);"
    "xhttp.send();}"
"</script>"
"</head>"
"<body onload=\"LoadSSE()\">"
"<div id='temperature'></div>"
"<div id='result' style='overflow:auto;width:200px;height:200px;border:solid 1px green;'></div>"
"<button onclick=\"CallApi('BOIL')\">Boil</button><br><br>"
"<button onclick=\"CallApi('STOP')\">Stop</button><br><br>"
"<button onclick=\"CallApi('REBOOT')\">Reboot</button><br><br>"
"<button onclick=\"CallApi('PUMP')\">Pump</button><br><br>"
"<button onclick=\"CallApi('DROP')\">Drop</button><br><br>"
"<button onclick=\"CallApi('POUR')\">Pour</button><br><br>"
"<button onclick=\"CallApi('RESET')\">Reset</button><br><br>"
"<button onclick=\"location.reload(true);\">Reconnect</button><br><br>"
"</body>"
"</html>";
